# Generated by Django 5.1.4 on 2025-01-30 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha_publicacion', models.DateField()),
                ('fecha_baja', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('nik', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('fecha_nac', models.DateField()),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha_publicacion', models.DateField()),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('categorias', models.CharField(max_length=100)),
                ('linkDrive', models.URLField(blank=True, null=True)),
                ('autores', models.ManyToManyField(related_name='autores', to='radiodb.autor')),
                ('programa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='podcast_programa', to='radiodb.programa')),
            ],
        ),
        migrations.CreateModel(
            name='MeGusta_Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='megusta_programa_programa', to='radiodb.programa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='megusta_programa_usuario', to='radiodb.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='MeGusta_Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podcast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='megusta_podcast_podcast', to='radiodb.podcast')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='megusta_podcast_usuario', to='radiodb.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Lista_Pendientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podcast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lista_pendientes_podcast', to='radiodb.podcast')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lista_pendientes_usuario', to='radiodb.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Lista_Escuchados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_escucha', models.DateField(auto_now_add=True)),
                ('podcast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lista_escuchados_podcast', to='radiodb.podcast')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lista_escuchados_usuario', to='radiodb.usuario')),
            ],
        ),
        migrations.AddConstraint(
            model_name='podcast',
            constraint=models.CheckConstraint(condition=models.Q(('categorias__in', ['Educativo', 'Comedia', 'Formación'])), name='categorias_check'),
        ),
        migrations.AlterUniqueTogether(
            name='megusta_programa',
            unique_together={('usuario', 'programa')},
        ),
        migrations.AlterUniqueTogether(
            name='megusta_podcast',
            unique_together={('usuario', 'podcast')},
        ),
        migrations.AlterUniqueTogether(
            name='lista_pendientes',
            unique_together={('usuario', 'podcast')},
        ),
        migrations.AlterUniqueTogether(
            name='lista_escuchados',
            unique_together={('usuario', 'podcast', 'fecha_escucha')},
        ),
    ]
