# Generated by Django 5.1.4 on 2025-02-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiodb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista_escuchados',
            name='fecha_escucha',
            field=models.DateField(),
        ),
    ]
