# Generated by Django 5.1.4 on 2025-02-21 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiodb', '0002_alter_lista_escuchados_fecha_escucha'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodosPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('numeroTarjeta', models.CharField(blank=True, max_length=16, null=True)),
                ('cvc', models.CharField(blank=True, max_length=3, null=True)),
                ('nombreTitular', models.CharField(blank=True, max_length=100, null=True)),
                ('correroTitular', models.EmailField(blank=True, max_length=254, null=True)),
                ('numeroCuenta', models.CharField(blank=True, max_length=24, null=True)),
                ('predeterminado', models.BooleanField()),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metodos_pago_usuario', to='radiodb.usuario')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('tipo__in', ['PagoTarjeta', 'Paypal', 'Transferencia'])), name='pagos_check')],
            },
        ),
    ]
